// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okojmmqpvjeotelnvyre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rb2ptbXFwdmplb3RlbG52eXJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MjYwMDUsImV4cCI6MjA2NjEwMjAwNX0.GECURoy2IgcPL2SaTStTtNZBOtWvj8RAr3V6FarXlow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);